LeaVerou/bliss

- .gitignore
- karma.conf.js
- package.json
- tests/CoreSpec.js
- tests/README.md
- tests/fixtures/core.html
Inital setup of testing framework
*Using:*
- Karma
- Mocha, with Chai
- html files for fixtures
- Phantomjs
- Chrome
Many more browsers can be added to Karma, even IE and such. This should be useful for Bliss.
The first test I put in asserts that fixtures can be loaded onto the DOM.
to run the tests, from the root of the project
```
npm install
karma start
```
> Setup tests

- tests/CoreSpec.js
- tests/DOM/SetSpec.js
This adds tests for the features that are unique to the `$.set` method, namely that it automatically sets properties and attributes.
It also cleans up some of the test setup related to fixtures, and includes a failing test for calling `set` on arrays. Issue incoming for that.
> Test the $.set method

- docs.html
It appears to have been copy/pasted from the description of `$.style` and didn't make sense in this context.
Also, two more missing commas.
> Update description of the first parameter to $.contents

- tests/DOM/ContentsSpec.js
Basic idea: create a test node `element`, add node(s) to it using `$.contents`, then assert that the length of `element.childNodes` is as expected. (If DOM nodes were directly added, we also check that the new child nodes are in fact the DOM nodes added.)
Repeat for `element._.contents` and `[elem1, elem2].contents`.
> Add $.contents tests (passing)

- tests/CoreSpec.js
- tests/events/DelegateSpec.js
Based on a test by @wcastand in LeaVerou/bliss#47. (Thanks!)
This seems to fail on PhantomJS due because `Element.matches` (used in `$.delegate`) is unavailable. Changing `$.delegate` to use `Element.webkitMatchesSelector` makes the test pass.
This test passes as is on Chrome and Firefox Developer.
> Add small test for $.delegate (failing on PhantomJS)

- style/prism.css
Code comments are styled with mix-blend-mode: multiply, which currently forces the whole page to be put into a blend mode composition surface, because nothing else on the page creates a stacking context. Doing blending on the whole page hurts performance. It also causes a performance problem specific to Firefox: Firefox doesn't support the "multiply" blend mode in the compositor yet, so it can't accelerate scrolling. (At least starting with Firefox 44 - Firefox up to version 43 has buggy accelerated multiply blending support, so it was turned off in Firefox 44, see bug 1135271.)
Adding isolation: isolate to the code section allows scrolling to be accelerated in recent Firefox versions and makes composition cheaper in all browsers.
> Use mix blend mode isolation on code sections.

- tests/DOM/CloneSpec.js
> Adding tests for $.clone()

- tests/DOM/BeforeSpec.js
* Removed usages of Bliss aside from $.before(), ._.before, and .set({before: _____})
* Used 3 sibling elements in each test such that $.before() was used to insert a new element between two existing siblings (BeforeSpec previously only used 2 elements in each test and therefore only checked that $.before() inserted an element before another but did not check if it was inserted IMMEDIATELY before the other)
* Tests are now run inside a fixture.
> Improved/Conventionalized BeforeSpec.js

- tests/DOM/AfterSpec.js
* Removed usages of Bliss aside from $.after(), ._.after, and .set({after: element})
* Used 3 sibling elements in each test such that $.after() was used to insert a new element between two existing siblings (AfterSpec previously only used 2 elements in each test and therefore only checked that $.after() inserted an element after another but did not check if it was inserted IMMEDIATELY after the other)
* Tests are now run inside a fixture.
> Improved/Conventionalized AfterSpec.js

- style/docs.css
This forces each of the current headings to span only one line, improving readability. For example:
Just wanted to check this has no negative side effects.
> Don't wrap text in table of contents

- docs.html
The documentation example for *$.ready* says:
```javascript
$$("div")._.style("border", "1px solid red");
````
instead of:
```javascript
$$("div")._.style({ border: "1px solid red" });
````
> Fix $.ready example in docs

- README.md
- docs.html
Inserted some code to explain how to previously check if a node retrieved by ```$``` is null, and how to avoid to apply chained methods in this scenario. I think this could be a useful note and it encourages the adoption of a variable as cached reference
the suggested code:
```
// Check if the .foo element exists
// and set an attribute by using a variable "foo"
// as a reference of the element
var foo;
if (foo = $(".foo")) {
foo.setAttribute("title", "yolo");
}
```
Note: as a side effect of this commit other lines are affected just because of the _autotrim_ function enabled on my ```Atom``` editor
> improvement on docs: suggestion about how to avoid errors when $ returns null

- bliss._.js
`this` is not guaranteed to be defined in `addEventListener`. A third-party lib was adding an event in a strange way which gave me the following error `Uncaught TypeError: Cannot read property '_' of undefined`.
> Fix for undefined `this` in event handlers

- tests/events/UnbindSpec.js
In response to issue #166, I added a couple of more tests for `Unbind`.  Please let me know if you see potential improvements.
> Added Unbind tests

- package.json
Sinon 1.17.4 is broken, see: https://github.com/sinonjs/sinon/issues/1040
We should downgrade to 1.17.3 for now, we have failing tests due to this bug.
> Downgrade Sinon due to bug in 1.17.4

- bliss.shy.js
- docs.html
`Bliss.fetch()` returns a Promise, via which one cannot access `xhr.abort()`. This PR attaches the xhr to the promise, so one can call `.abort()`. This is a little bit hacky ... but the [HTML5 fetch API & abort stuff](https://developer.mozilla.org/en-US/docs/Web/API/FetchController) looks complicated and is experimental, so perhaps this PR is the best approach for now.
Discussed in this issue: https://github.com/LeaVerou/bliss/issues/198
Right now this PR includes only Bliss.Shy.js — shall I run some build script so the `.min.js` files get updated too, + update the "thick" Bliss js file too? Or do you want to do that (Lea) ?
> Expose xhr.abort() from Bliss.fetch().

- .eslintrc.json
- package.json
- tests/arrays/AllSpec.js
- tests/arrays/EachSpec.js
- tests/objects/LazySpec.js
This ensures "block-like" statements are padded with a blank line unless they are variable declarations, using the [padding-line-between-statements](https://eslint.org/docs/4.0.0/rules/padding-line-between-statements)-rule introduced in eslint 4.0.0.
"block-like" means "statements that the last token is the closing brace of blocks; e.g. { }, if (a) { }, and while (a) { }."
This will pass for example:
```js
var foo = "bar";
var baz = function() {
...
};
```
And also:
```js
if (expression) {
...
}
else if (expression2) {
...
}
```
But not:
```js
if (expression) {
...
}
if (expression2) {
...
}
```
or:
```js
var foo = function() {
...
};
foo();
```
Limitations:
Does not apply to object methods. There is a separate issue/suggestion for that called "padded-object", but it's not implemented …
> Add linting to ensure line-breaks between "block-like" statements

- bliss.js
- bliss.shy.js
This enables unsetting Bliss' default Content-type (see #202) by passing options:
```js
{headers: {"Content-Type": undefined}}
```
Notes:
1. As you can see, another condition was needed `env.headers[header] !== undefined`. This is because xhr.setRequestHeader treats `undefined` value as `"undefined"` (string). I can make this more explicit if you want (only for "Content-Type" and "Content-type"), but I think it may be going too far for compatibility. I doubt there are any valid case where you'd want to set headers to "undefined" (or am I wrong?), and if you do, you can still pass `"undefined"` instead of `undefined`.
2. I purposely excluded the minified js this time, in order to avoid conflicts.
> Enable unsetting Bliss' default Content-type by passing undefined

- bliss.js
- bliss.shy.js
As per discussion in #204.
I was a little bit unsure if `env.xhr.upload` would always be present. I think it always should be regardless of existence of a "body" (for example GET requests), and my tests (latest versions of Chrome, Firefox, Edge, Safari + IE11) confirms this, but I still felt uneasy not checking.
There is no parameter validation besides checking that `upload` is an object. The intention was just to provide access to attaching events to xhr.upload via `$.fetch()`s option params, similar to how it can be done with download events today. Not taking responsibility for how people use it. Unlike the xhr-object, xhr.upload doesn't have any read only-properties, so `try...catch` shouldn't be necessary (at least for that reason) unless the xhr standard changes.
> Fixes 204: $.fetch() upload events

- .eslintrc.json
- bliss._.js
- bliss.shy.js
- tests/DOM/CloneSpec.js
- tests/DOM/InsideSpec.js
- tests/DOM/PropertiesSpec.js
- tests/DOM/QuerySelectorAllSpec.js
- tests/DOM/QuerySelectorSpec.js
- tests/DOM/StartSpec.js
- tests/DOM/StyleSpec.js
- tests/arrays/AllSpec.js
- tests/arrays/EachSpec.js
- tests/events/DelegateSpec.js
- tests/events/ReadySpec.js
- tests/events/UnbindSpec.js
- tests/objects/AddSpec.js
- tests/objects/ExtendSpec.js
- tests/objects/FetchSpec.js
- tests/objects/HooksSpec.js
- tests/objects/LazySpec.js
- tests/objects/LiveSpec.js
- tests/objects/OverloadSpec.js
- tests/objects/ValueSpec.js
A lot of existing code breaks the editorconfig settings (especially in the tests), which makes it hard for contributors using editorconfig integrated editors/IDEs to change something small without also changing formatting for the whole file.
This PR does:
* Add eslint-rule "no-trailing-spaces" (it's already an editorconfig-setting, but not enforced in eslint).
* Removes trailing spaces and converts all indentation to tabs in bliss source files (bliss._.js and bliss.shy.js) and tests
It doesn't:
* Add any eslint-rule for indentation (bliss.shy.js and bliss._.js aren't correctly indented and this looks like it's possibly intentional)
* Format other files such as gulpfile.js, index.js, style/prism.js or transform.js that are not in `files` in karma.conf.js (and hence not tested)
> Apply editorconfig settings to current code

- .eslintrc.json
- bliss.shy.js
- tests/arrays/EachSpec.js
Eslint will now warn if declaring multiple variables in the same statement, except if all of them are uninitialized. For example, this is still valid:
`var testContainer, para0, para1, para2;`
(There are a lot of these in the test specs and splitting them up isn't necessarily better imo)
> Linting: Force splitting variable declaration for initialized vars

- .eslintrc.json
Don't force blank lines after block-like statements, as per discussion in https://github.com/LeaVerou/bliss/pull/209#issuecomment-343298129
> Don't force blank lines after block-like statements

- bliss.shy.js
- docs.html
if neither event type nor callback has been given, remove all stored listeners from an element regardless of capture value setting. This avoid iterating through the arrays twice for cleaning up, once for capture=true and once for capture=false.
> remove all listeners unconditionally and fixed [#221]

- index.js
If the URL ends with "/docs.html", the TOC will show up, but with just "/docs", it doesn't show up. This PR intends to fix this discrepancy.
Fixes #256
> Fix table of contents not showing
