LeaVerou/bliss

docs.html
index.html

Not sure if that's the intention but I reckon you were thinking of linking it.

Linkify 'Blog post' to the article 😄

---

package.json
tests/CoreSpec.js
tests/DOM/CreateSpec.js

Relevant for #1 (might even close it?)
Testing the basic functionality of `$.create` to get the ball rolling and to avoid more people writing tests on top of each other :)
I organized this in folders based on topics in the documentation, and one file per method.
See the commit messages for details on the other changes.

Test the $.create method

---

bower.json

was breaking with:
> bower EMALFORMED Failed to read F:\...\bliss\bower.json
> Additional error details:
> Unexpected string

typo preventing bower update

---

package.json

Start karma with npm test

---

docs.html

Add missing commas and semicolons to $.set example

---

tests/DOM/CreateSpec.js

Adds a test for #13. Now we don't have to hope it works ^^

Test that $.create makes a div by default

---

bliss.js
bliss.shy.js

This PR simply trims trailing spaces (or rather tabs), which don't have to be there.

Trim spaces

---

.editorconfig

Followup on https://github.com/LeaVerou/bliss/commit/4c82f3d4edb39842660380b6100afef34821f238#commitcomment-14817569

the display of tabsize is a matter of preference

---

tests/DOM/AroundSpec.js

Add $.around tests (passing)

---

tests/DOM/AttributesTest.js

 Add $.attributes tests (passing)

---

style/docs.css

This resolves the problem @dperrymorrow describes in #54.

Fix TOC z-index issue (see #54)

---

package.json

rather than a dependency of karma-sinon
per request from @zdfs under #46

adding sinon directly

---

README.md

build and test instructions

---

tests/objects/LazySpec.js

issue #46 
tests for ```$.lazy```

tests for $.lazy

---

tests/events/EventsSpec.js

Test are not working with handlers.
Test are working by cloning element only with the click event.
(only tested , oninput, onclick and onchange)

Add test for $.events

---

README.md

Cudos to https://github.com/github/fetch.
I've just guessed that it is 6.1+ for Safari, but it could be 6 as well: http://caniuse.com/#compare=ie+9,safari+5.1,safari+6,safari+6.1&compare_cats=HTML5,JS%20API,Other
This is how it looks like: https://github.com/kurtextrem/bliss/tree/patch-2

Add browser support table

---

tests/events/FireSpec.js

I don't know if the second test with params needed so much test.
So let me know if it's too much, or if there is better way to do it. :)

Add test for $.fire

---

tests/DOM/StyleSpec.js

Initial tests for `$.style` on elements, arrays, and `ELEMENT._.style` and `ARRAY._.style`.

First tests for $.style

---

docs.html

```javascript
var ret = array._.all(array, method [, args...])
```
should be
```javascript
var ret = array._.all(method [, args...])
```

Remove whitespace from docs.html and fix array._.all signature documentation

---

tests/arrays/EachSpec.js

Adds tests for the $.each() method.

Initial commit of each method

---

.travis.yml

installs latest stable google chrome along with it's dependencies and runs test on that.

fix : #117

---

.travis.yml

Run single Travis CI job

---

tests/events/UnbindSpec.js

Setup up test structure to test $unbind function

Test case for $.unbind #166 #156

---

docs.html

Fix a typo

---

index.html

Update polyfill URL from v2 to v3

Update polyfill URL

---

README.md

Also use reference links to improve the readability in source mode.

[README.md] Add Edge to browser support, fix browser icon urls

---

src/dom/contents.js

It looks like expressions `type = type(...)` are not valid anymore.

Fix issue with $.contents()

---

src/dom/create.js
src/dom/set.js
src/overload.js

Fix issues with $.overload(), $.set(), and $.create()
